name: DokuWiki Default Tasks
on:
  push:
  pull_request:
  schedule:
    - cron: '25 8 10 * *'


jobs:
  all:
    uses: dokuwiki/github-action/.github/workflows/all.yml@main

  js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run lint
      - run: npm test
